### ISSUE TITLE
`keepInventory` has no effect

### ISSUE THREAD

**Issue by LTCatt** [CalaMariGold/ConfigurableDeath#1]
![image](https://github.com/CalaMariGold/ConfigurableDeath/assets/40348278/5db61b48-05ba-4f55-8618-9e40b50b6153)

I still drop all items on death.

Version: 1_20_1-1.0.0

**Comment by LTCatt** [comment]
Hello, is this mod discontinued? Is there any plan fixing this?
Since this bug also breaks the `keepInventory` game rule, it makes this mod completely unusable :/

**Comment by mocacola02** [comment]
I'm having the same problem. I would really like the mod to work, there's nothing else like it (the Configurable Keep Inventory mod just crashes). Items drop no matter what, and get deleted on top of that.

**Comment by CalaMariGold** [comment]
im gonna need more info. do you have any other mods in the instance? did you try just enabling keepInventory? is the gamerule disabled?

**Comment by LTCatt** [comment]
![image](https://github.com/CalaMariGold/ConfigurableDeath/assets/40348278/20521873-e983-4faa-8cbf-5d0317e9c43e)
![image](https://github.com/CalaMariGold/ConfigurableDeath/assets/40348278/ca6e2ea6-1275-449b-8de6-526f257dc583)

With a default config file, a newly created world, and only this mod, all items disappear on death and no items drop.

**Comment by LTCatt** [comment]
![image](https://github.com/CalaMariGold/ConfigurableDeath/assets/40348278/04cd015b-3ca2-4b84-a457-793102ca61e4)

CurseForge comments also mentioned this bug :/

**Comment by mocacola02** [comment]
In my case, I have a fair number of mods installed. With keepInventory on, the items are cleared from my inventory. With keepInventory off, items are dropped on the ground despite the mod config having keep inventory on, but when picked up the items do not actually enter my inventory. I'm away from my PC right now, but I can post the modlist later if that helps.

**Comment by mocacola02** [comment]
Here are all the mods I use, if that helps. This is on Forge 47.2.30 for Minecraft 1.20.1 (note that this list is without configurable death installed, this is every mod other than configurable death)
![image](https://github.com/CalaMariGold/ConfigurableDeath/assets/95735686/ff96f465-a3ef-45ce-989d-ef72ea41dccc)

**Comment by mocacola02** [comment]
I solved it. Having all of the itemDrops config settings set to true breaks it. Setting ONLY keepInventory fixes it. I understand what you mean by "did you try just enabling keepInventory" now (I misunderstood that for vanilla's gamerule). I would suggest maybe just a warning that you only need that one or the other options, but that's up to you, I just think it would help clarify what each option does. Thanks for checking on the issue!

**Comment by LTCatt** [comment]
In the default configuration of this mod, all `itemDrops` settings are true. This could be quite misleading...

**Comment by CalaMariGold** [comment]
Default config for inventory settings are all false. There should be clarification on this though. In the mean time, I'll update the curseforge page. Thanks everyone!
